### ISSUE TITLE
logic

### ISSUE THREAD

**Issue by linkboy2500** [MetroidPrimeModding/PrimeRandomizerItemHelper#7]
there should be a logic tab or something that shows you what items you can get with your current gear, and if that already exists how do i use it

**Comment by Pwootage** [comment]
This actually used to be a feature of the original version of this project, circa 2015, and the code actually still exists in the repository for that version. However, several randomizer versions later, it does not work with modern log formats. Some of the other available trackers might have this feature - although I personally haven't checked.

I have no plans on updating this project at this time.

It could probably be done, but that part of the project could also use a rewrite into either plain JS or a more modern Angular rather than an ancient version of angularJS. It also likely needs a logic update, there's probably a few new ways that have been found to obtain things.
